apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-vmsvc-auth
spec:
  secretTargetRef:                             
  - parameter: userName 
    name: mypgdb-pguser-mydb-admin
    key: user
  - parameter: password 
    name: mypgdb-pguser-mydb-admin
    key: password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-vmsvc-scaledobject-pg
spec:
  scaleTargetRef:
    name: keda-vmsvc-deployment
  pollingInterval: 10   # Optional. Default: 30 seconds
  cooldownPeriod: 30    # Optional. Default: 300 seconds
  maxReplicaCount: 10   # Optional. Default: 100
  triggers:
    - type: postgresql
      metadata:
        host: 10.220.8.9 
        port: "5432"
        dbName: mypgdb
        sslmode: require
        query: "SELECT COUNT(*) FROM cities;"
        targetQueryValue: "1"
      authenticationRef:
        name: keda-vmsvc-auth